### ISSUE TITLE
OSM Rebranding- Settings button in typography is of no use, since styling tab is removed from scope now.

### ISSUE THREAD

**Issue by bagrinsergiu** [EasyBrizy/Brizy-Local-Editor#104]
Styling button in typography is of no use, since styling tab is removed from scope now.

**Comment by bagrinsergiu** [comment]
Duplicate of: https://github.com/EasyBrizy/Brizy-Local-Editor/issues/95 

Right?

**Comment by maxval1** [comment]
fixed here: https://github.com/EasyBrizy/Brizy-Local-Editor/pull/111
