### ISSUE TITLE
i was validating the Build V2.1.21 using demo Brizy CDN. For elements where you have added the option to add the onclick handler, I am not seeing this for the close button, which is a measure use case for us to track the event when user click on close button.

### ISSUE THREAD

**Issue by bagrinsergiu** [EasyBrizy/Brizy-Local-Editor#108]
![image](https://user-images.githubusercontent.com/5760683/220866324-8c5c24fd-ae98-42b8-be93-330ca82c6ebf.png)

![image](https://user-images.githubusercontent.com/5760683/220867348-efcaa84a-ad7a-4b72-b347-fd17c5b2b800.png)

![image](https://user-images.githubusercontent.com/5760683/220867546-a243ea1e-bfd5-429c-b886-890e38bbd665.png)

**Comment by maxval1** [comment]
Fixed in v2.2.23
