### ISSUE TITLE
Settings ->Styling/Effects  tabs are not visible

### ISSUE THREAD

**Issue by bagrinsergiu** [EasyBrizy/Brizy-Local-Editor#109]
1.Settings ->Styling/Effects  tabs are not visible unless user clicks hovers on it. -Regression
https://app.birdeatsbug.com/sessions/jRNUJzeEHxRrYNcJczTQIqt67eNYZmRcynxOgXXjUd1X

**Comment by maxval1** [comment]
fixed here: https://github.com/EasyBrizy/Brizy-Local-Editor/pull/111
