### ISSUE TITLE
Background address is not coming by default on mWeb /tablet view

### ISSUE THREAD

**Issue by bagrinsergiu** [EasyBrizy/Brizy-Local-Editor#110]
Background address is not coming by default on mWeb /tablet view.- Old behaviour only
https://app.birdeatsbug.com/sessions/v6Iszre7q3cGUB2N-SPK7yIo9gSv17GP4h-pBRWUc5NG

**Comment by DimiBaitanciuc** [comment]
1.Map is not rendered in mWeb.

a.Select a blank template.

b.In column editor, navigate to background, under type select geo-location.

**Expected**: 
The location selected in web should be displayed mWeb.

**Actual**: 
The map is not rendered in mWeb as well as on SDK.

**Steps**:
https://app.birdeatsbug.com/sessions/XLW9S5OAxpJysFEBigyIHC2xw17NjimnW2cQSxVIRj4D

**Comment by varvaraporubin** [comment]
verificat
