### ISSUE TITLE
OSM Rebranding- Focal point is displayed when background image is added for column/canvas or template editor.

### ISSUE THREAD

**Issue by DimiBaitanciuc** [EasyBrizy/Brizy-Local-Editor#122]
Steps to reproduce:
1.Add a image/gallery element.

2.Add a proper image file

**Expected**: 
When a custom image is uploaded, focal point should be present.

**Actual**: 
After uploading the image, focal point is missing.

**Note**: 
For column/canvas editor, when a custom image is uploaded, focal point is present.

Steps: https://app.birdeatsbug.com/sessions/yH6bG7ZKn1sF-b8kGeBpTu0qrhwDmyRkccjCnbxNDMjE

**Comment by ravithejabandari-ME** [comment]
@DimiBaitanciuc Let's remove the focal point feature from everywhere as we are not targeting to have it as a part of initial launch and imagekit doesn't support focal point.
