### ISSUE TITLE
Page behind interaction 

### ISSUE THREAD

**Issue by bagrinsergiu** [EasyBrizy/Brizy-Local-Editor#80]
1. Page behind interaction is not working correctly in the editor. Brizy to look into this bug. https://jmp.sh/ciKgtA8E
2. Click outside the Banner is not working it is related to point 2

**Comment by bagrinsergiu** [comment]
Each popup has to fulfill 4 mandatory things, right?
1. Be responsive :: Demo: https://www.loom.com/share/856184df693648d4ac18fe17e01f1e40
2. Scroll behind must work for the main page :: Demo :: https://www.loom.com/share/22b8934b988a41269ba92cd1bca06875
3. Allow events to reach the main page :: Demo :: https://www.loom.com/share/1a49c503dd3a47988a6fd58b2cf8d29c
4. Events must work inside the popup :: Demo :: https://www.loom.com/share/97919e18a83e4720ad95658c55a0c951
it's not technically possible to solve all 4 points and embed in iframe
[@ajeet](https://brizy.slack.com/team/U021K4AEGPN)
 - You must have dropped one of the points. The question is which one?

**Comment by bagrinsergiu** [comment]
This solution will not work for us, as we are embedding the template in an iframe at our SDK side that we can not change for now. We have discussed internally and come to an approach that will work for us. In case of Banner template (embedded: true) could you please provide a drop down in the builder for positioning (TOP, CENTER, BOTTOM, e.t.c) and whatever position user selected the Banner will be positioned accordingly in the preview and the this position should not be part of the Html or pageData, please add a new key like Position  in the output, we will use the position value to render the template accordingly at our SDK side.
Attaching the Video reference for the same
cc: 
[@Amol](https://brizy.slack.com/team/UH9NA7QJ0)
 
[@Roopal Yadav](https://brizy.slack.com/team/U044DN3J6J3)
 
[@Ravitheja Bandari](https://brizy.slack.com/team/U03MSHH3C74)

Please look into this fix, it is blocker for us to implement Banner template.

**Comment by bagrinsergiu** [comment]
### In this case, I need an example of HTML that meets all 4 cases + iframe

1. Be responsive :: Demo: https://www.loom.com/share/856184df693648d4ac18fe17e01f1e40
2. Scroll behind must work for the main page :: Demo :: https://www.loom.com/share/22b8934b988a41269ba92cd1bca06875
3. Allow events to reach the main page :: Demo :: https://www.loom.com/share/1a49c503dd3a47988a6fd58b2cf8d29c
4. Events must work inside the popup :: Demo :: https://www.loom.com/share/97919e18a83e4720ad95658c55a0c951

**Comment by maxval1** [comment]
[@Ravitheja Bandari](https://brizy.slack.com/team/U03MSHH3C74)

For All templates:
1. Provide configurations to remove 'click outside to close', 'scroll page behind' options.

For Banner template:
1. Provide a drop down in the builder for positioning (TOP, CENTER, BOTTOM, e.t.c) and whatever position user has selected the Banner should be positioned accordingly in the preview. This position should not be part of the Html or pageData, please add a new key like 'Position' in the output, Moengage will use the 'Position' value to render the template accordingly at the SDK level.
2. Remove the 'push content option' if the above configuration is provided

**Comment by maxval1** [comment]
For Banner template:
1. Remove the 'push content option' if the above configuration is provided https://github.com/bagrinsergiu/blox-editor/issues/21841

**Comment by maxval1** [comment]
Popup position fixed here https://github.com/EasyBrizy/Brizy-Local-Editor/pull/96
included in the latest version `2.1.21`
