### ISSUE TITLE
Elements Events

### ISSUE THREAD

**Issue by bagrinsergiu** [EasyBrizy/Brizy-Local-Editor#81]
![image](https://user-images.githubusercontent.com/5760683/218993510-51005d39-29c9-429a-8bf0-f1ddd999970a.png)

**Comment by bagrinsergiu** [comment]
@Maxim 

My colleague 
[@Victor Poalelungi](https://brizy.slack.com/team/U04MHD4T231)
 added functionally for Submit Button the click handler and store your code on the JSON page data, in export this code are executed when the user is clicked the submit button, I want to know if is this functional enough?

**Comment by maxval1** [comment]
Brizy Elements

| ElementName   | Need to be added | Status         |
|:--------------|:-----------------|:---------------|
| Row           | ?                | unknown        |
| Column        | ?                | unknown        |
| Text          | ?                | unknown        |
| Button        | +                | In progress... |
| Icon          | +                | In progress... |
| Spacer        | ?                | unknown        |
| Line          | ?                | unknown        |
| Map           | ?                | unknown        |
| Embed         | ?                | unknown        |
| Form          | ?                | unknown        |
| IconBox       | ?                | unknown        |
| Counter       | ?                | unknown        |
| Countdown     | ?                | unknown        |
| Tabs          | ?                | unknown        |
| Progress      | ?                | unknown        |
| Accordion     | ?                | unknown        |
| Alert         | ?                | unknown        |
| Menu          | ?                | unknown        |
| Rating        | ?                | unknown        |
| Table         | ?                | unknown        |
| Timeline      | ?                | unknown        |
| Switcher      | ?                | unknown        |
| Lottie        | ?                | unknown        |
| Calendly      | ?                | unknown        |
| Image         | +                | In progress... |
| Gallery       | ?                | unknown        |
| Audio         | ?                | unknown        |
| Carousel      | ?                | unknown        |
| Video         | ?                | unknown        |
| Playlist      | ?                | unknown        |
| Facebook      | ?                | unknown        |
| Twitter       | ?                | unknown        |
| Comments      | ?                | unknown        |

**Comment by maxval1** [comment]
Fixed in `v2.1.21` https://github.com/EasyBrizy/Brizy-Local-Editor/blob/master/packages/core/docs/self-hosted.MD#trigger-parameters
