### ISSUE TITLE
Could you please remove the #  or any new character once introduce to trigger the richtext from the Builder Preview as it is there in the below screenshot.

### ISSUE THREAD

**Issue by bagrinsergiu** [EasyBrizy/Brizy-Local-Editor#83]
![image](https://user-images.githubusercontent.com/5760683/218994558-8a0b1785-8e5d-465a-9f75-b9f8cc2064ba.png)

**Comment by bagrinsergiu** [comment]
please create an issues on GitHub for these Personalisation issues
https://xxx.slack.com/archives/C04HHHJ1M32/p1676032239956219?thread_ts=1674726554.155619&cid=C04HHHJ1M32
https://xxx.slack.com/archives/C04HHHJ1M32/p1676032605346269?thread_ts=1674726554.155619&cid=C04HHHJ1M32
https://xxx.slack.com/archives/C04HHHJ1M32/p1676045124696559?thread_ts=1674726554.155619&cid=C04HHHJ1M32


ajeet
[@Sergiu](https://brizy.slack.com/team/UASEWGEJV)
 
[@Alex](https://brizy.slack.com/team/U9A5QE1A6)
 There is one issue which i am facing in the Builder in personalisation integration, when we are passing below mentioned textContent
const textContnet = ContentApi.Delhi_Weather({({"params":{"q":"Delhi","appid":"123"},"static_params":{},"dynamic_params":{},"request_body":{}})});
to the richText callback method  res({label:textContnet,placeholder:textContnet }) , in the final html output the content is getting changed. Adding the changed output value and screenshot also.
Final html output has the below value
Show more
Screenshot 2023-02-10 at 5.59.06 PM.png
 
Screenshot 2023-02-10 at 5.59.06 PM.png


[From a thread in brizy-tech-discussion](https://xxx.slack.com/archives/C04HHHJ1M32/p1676032239956219?thread_ts=1674726554.155619&amp;cid=C04HHHJ1M32) | [Feb 10th](https://xxx.slack.com/archives/C04HHHJ1M32/p1676032239956219?thread_ts=1674726554.155619&amp;cid=C04HHHJ1M32) | [View reply](https://xxx.slack.com/archives/C04HHHJ1M32/p1676032239956219?thread_ts=1674726554.155619&amp;cid=C04HHHJ1M32)


ajeet
[@Sergiu](https://brizy.slack.com/team/UASEWGEJV)
 
[@Alex](https://brizy.slack.com/team/U9A5QE1A6)
 Could you please remove the #  or any new character once introduce to trigger the richtext from the Builder Preview as it is there in the below screenshot. This # is not part of html (i.e as expected) but after promise get successfully resolve it should also not be shown in the preview.
cc: 
[@Amol](https://brizy.slack.com/team/UH9NA7QJ0)
 
[@Ravitheja Bandari](https://brizy.slack.com/team/U03MSHH3C74)
 
[@Sukirti](https://brizy.slack.com/team/U032U0DHZ2R)
 (edited) 
Screenshot 2023-02-10 at 6.01.50 PM.png
 
Screenshot 2023-02-10 at 6.01.50 PM.png


[From a thread in brizy-tech-discussion](https://xxx.slack.com/archives/C04HHHJ1M32/p1676032605346269?thread_ts=1674726554.155619&amp;cid=C04HHHJ1M32) | [Feb 10th](https://xxx.slack.com/archives/C04HHHJ1M32/p1676032605346269?thread_ts=1674726554.155619&amp;cid=C04HHHJ1M32) | [View reply](https://xxx.slack.com/archives/C04HHHJ1M32/p1676032605346269?thread_ts=1674726554.155619&amp;cid=C04HHHJ1M32)


ajeet
[@Victor Poalelungi](https://brizy.slack.com/team/U04MHD4T231)
 
[@Sergiu](https://brizy.slack.com/team/UASEWGEJV)
 
[@Alex](https://brizy.slack.com/team/U9A5QE1A6)
 there is one more issue i am facing in this, Attaching the screenshot for the same.
const textContnet = {% if ProductSet.Sweta_productset%}{% for product in ProductSet.Sweta_productset%}{% endfor %}{% else %}xxx_NOT_SEND{% endif %}
when we are calling the richtext callback method res({label:textContnet,placeholder:textContnet})  in the final html output the textContent is getting changed. Attaching the screenshot for the same, if you see in the below screenshot the data-population  attribute value is correct but the p tag text content has an extra {{  and }}. Please look into this. cc: 
[@Amol](https://brizy.slack.com/team/UH9NA7QJ0)
 
[@Ravitheja Bandari](https://brizy.slack.com/team/U03MSHH3C74)
 (edited) 
Screenshot 2023-02-10 at 9.25.04 PM.png
 
Screenshot 2023-02-10 at 9.25.04 PM.png

**Comment by bagrinsergiu** [comment]
### 1. Remove the [#]

https://i.imgur.com/MRcQyqu.png

https://i.imgur.com/77Ynivz.png

https://i.imgur.com/HyM3jZx.png

### 2.  The final html output the textContent is getting changed

const textContnet = {% if ProductSet.Sweta_productset%}{% for product in ProductSet.Sweta_productset%}{% endfor %}{% else %}xxx_NOT_SEND{% endif %}


https://i.imgur.com/txySC7z.png

https://i.imgur.com/rceBvyC.png

### 3. when we are passing below mentioned textContent

const textContnet = ContentApi.Delhi_Weather({({"params":{"q":"Delhi","appid":"123"},"static_params":{},"dynamic_params":{},"request_body":{}})});


---

There is not a problem. `Res` function is not using correctly, valid example:
`res( { label:"YOUR CUSTOM LABEL", placeholder: "{{ YOUR_CUSTOM_PLACEHOLDER }}" } )`

https://i.imgur.com/7hQKpgT.png

**Comment by ajeetmoengage** [comment]
@bagrinsergiu 
2. The final HTML output the textContent is getting changed
3. when we are passing below mentioned textContent

There is an issue in this case, in the dom https://i.imgur.com/rceBvyC.png is correct, but the Builder output that we are getting on save there the output is getting changed. Please look into this.

**Comment by victor-pg** [comment]
@ajeetmoengage We have added a new key for this case: `withCustomPlaceholder` https://github.com/EasyBrizy/Brizy-Local-Editor/blob/master/packages/core/docs/cdn.MD#dynamiccontent-parameters
Try please to use with `withCustomPlaceholder: true`: https://i.imgur.com/jhYV1AM.png.
In next update we will set this key to be `true` by default.
