### ISSUE TITLE
Onclick on all the elements not only the form elements.

### ISSUE THREAD

**Issue by bagrinsergiu** [EasyBrizy/Brizy-Local-Editor#84]
Onclick on all the elements not only the form elements.  https://brizy.slack.com/archives/C04HHHJ1M32/p1676461877611339?thread_ts=1676268974.920909&cid=C04HHHJ1M32

**Comment by bagrinsergiu** [comment]
1. You need to create a documentation how exactly the events should work in the interface (where you click what appears, ...), 

2. On which elements we should add events.

**Comment by maxval1** [comment]
fixed in `2.1.21` 
https://github.com/EasyBrizy/Brizy-Local-Editor/blob/master/packages/core/docs/self-hosted.MD#trigger-parameters
