### ISSUE TITLE
Theming of editor 2.1.20

### ISSUE THREAD

**Issue by bagrinsergiu** [EasyBrizy/Brizy-Local-Editor#89]
have validated the build 2.1.20, few things is not working as expected for theming of editor
we require background and icon color different on onHover/active state as shown in the below design

![image](https://user-images.githubusercontent.com/5760683/219600115-7d6d9839-19b4-46cf-8a9d-1d3e98c7b2dd.png)

![image](https://user-images.githubusercontent.com/5760683/219600138-253fa118-7d31-4274-942b-d2d85db016c7.png)

currently it is changing icon color only

![image](https://user-images.githubusercontent.com/5760683/219600197-d97275c8-cc4b-4da9-bea6-e0682a8153da.png)

![image](https://user-images.githubusercontent.com/5760683/219600245-75ffd821-b0b1-4b4b-88e6-4e883b5a37ff.png)

and also is it possible to modify search bar like this

![image](https://user-images.githubusercontent.com/5760683/219600282-9215f8a3-c960-410f-9bd4-99c39d1e3cd4.png)

currently it is looking like this

![image](https://user-images.githubusercontent.com/5760683/219600324-8a53f3a6-35ba-4849-9cda-fa8b918385d2.png)

**Comment by bagrinsergiu** [comment]
We will investigate if it can be done. It needs changes in the components, not just styling.

**Comment by maxval1** [comment]
@DimiBaitanciuc 
We have discussed about this already, the theming is only changing colors to our existing UI. These modifications involve major changes in how our componenets work across all our products and can't be done.

**Comment by DimiBaitanciuc** [comment]
@maxval1 on this issue we need to fix the search: 

- we **DO NOT** change the structure of the component like here: https://jmp.sh/AQc6gQ1U
- we add the border we currently have: https://jmp.sh/xrjULO5y because when you change styling to white the search looks like it floats: https://jmp.sh/lCJZuqWc
