### ISSUE TITLE
[Fixes] Menu example 

### ISSUE THREAD

**Issue by bagrinsergiu** [EasyBrizy/Brizy-Local-Editor#90]
could you please send us an example for creating a menu, i was trying with some dummy data but it is not working. Attaching the video reference for the same.

**Comment by bagrinsergiu** [comment]
Why do you need a menu element in Popup? Maybe we should disable the element?

**Comment by maxval1** [comment]
Let's disable it

**Comment by maxval1** [comment]
Fixed in `2.1.21`
