### ISSUE TITLE
Tool tip missing for Settings in Container of Gallery Element

### ISSUE THREAD

**Issue by bagrinsergiu** [EasyBrizy/Brizy-Local-Editor#92]
Tool tip missing for Settings in Container of Gallery Element  , Overall template customisation on top right, close button
Gif file : https://app.birdeatsbug.com/sessions/pjUzs-4wU6SmbKDAsLXXbbOP-5CdXWShgoSXyDzhrkQ7

https://github.com/bagrinsergiu/blox-editor/issues/21921

**Comment by maxval1** [comment]
Fixed in `2.1.21`
