### ISSUE TITLE
In Text element, under typography, custom text button doest work

### ISSUE THREAD

**Issue by bagrinsergiu** [EasyBrizy/Brizy-Local-Editor#93]
In Text element, under typography, custom text button doest work/ If it is a tooltip, then why does user have to click on it, it should be available on just by hovering on it.
Gif file :[Plum Snail](https://app.birdeatsbug.com/workspaces/4a7acbec-ef53-4214-8dbb-e0e1f209693f/collections/44a657fb-7dad-443c-a36e-43d4559c9399/sessions/D1U6Am9Umw2Li7ryrMq5MgYStsNHIkug0D6mkXKlTi-o)

https://github.com/bagrinsergiu/blox-editor/issues/21923

**Comment by maxval1** [comment]
Fixed in `2.1.21`
