### ISSUE TITLE
If all elements are deleted , editor becomes unusable

### ISSUE THREAD

**Issue by bagrinsergiu** [EasyBrizy/Brizy-Local-Editor#94]
If all elements are deleted , editor becomes unusable unless the editor is reloaded again
Gif file :https://app.birdeatsbug.com/sessions/pFe6d1gOsNquEllU5u3UG4MNMzihgZB0o249526hQbyi

https://github.com/bagrinsergiu/blox-editor/issues/21924

**Comment by maxval1** [comment]
Fixed in `2.1.21`
