### ISSUE TITLE
Settings button in typography is of no use

### ISSUE THREAD

**Issue by bagrinsergiu** [EasyBrizy/Brizy-Local-Editor#95]
Settings button in typography is of no use, since styling tab is removed from scope now.
https://app.birdeatsbug.com/sessions/7H-39p2d-YfdQEkXG-WIRJajyuikXLjDaKqYQXJSWMR7

https://github.com/bagrinsergiu/blox-editor/issues/21925

**Comment by maxval1** [comment]
Fixed: here https://github.com/EasyBrizy/Brizy-Local-Editor/pull/111
