### ISSUE TITLE
[Fixes] OSM Rebranding- Platforms preview option is not properly aligned

### ISSUE THREAD

**Issue by bagrinsergiu** [EasyBrizy/Brizy-Local-Editor#99]
https://i.imgur.com/FHaq8Zd.png

**Comment by ravithejabandari-ME** [comment]
@DimiBaitanciuc The option to select Mobile view is not properly visible and accessible, hence it is of top priority.

**Comment by DimiBaitanciuc** [comment]
@ravithejabandari-ME I agree now that I understand what the issue is :). 

The title said only alignment with no other explanations. Please be so kind and explain more context on issues, otherwise we might not put the right urgency on it. 

Got it, all good.
